version: '3'
services:
  shop:
    image: timhard/shabu-shop:latest
    ports:
     - "8010:8010"
    links:
      - products
      - stock
  products:
    image: timhard/shabu-products:latest
    ports:
     - "8020:8020"
  stock:
    image: timhard/shabu-stock:latest
    ports:
     - "8030:8030"
